version: '3.4'
services:
  alpha:
    build: 
      context: ./ServiceAlpha
    ports:
      - "8081:8081"
    environment:
      JAEGER_AGENT_HOST: jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - jaeger

  beta:
    build: 
      context: ./ServiceBeta
    ports:
      - "8082:8082"
    environment:
      JAEGER_AGENT_HOST: jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://beta:8082/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - jaeger
  
  krakend:
    image: devopsfaith/krakend:2.1.3
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - alpha
      - beta
      - jaeger
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - alpha
      - beta
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  grafana-data: