name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build-and-push: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: set up java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: microsoft

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Build Docker Image
        run: docker build . --file Dockerfile -t ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Login into the Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push tag to Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}